name: Continuous Integration

on: ['push', 'pull_request']

permissions:
  contents: write

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2 #match with project
          tools: composer:v2, povils/phpmnd, laravel/pint, larastan/larastan
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: PHP Magic Number Detector
        run: vendor/bin/phpmnd . --exclude tests

      - name: Pint
        run: pint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Pint Fixes'

      - name: PHPStan
        run: phpstan analyse app/ --error-format=github
