name: Deploy Ephemeral Staging

on:
  workflow_dispatch:
    inputs:
      ttl:
        type: number
        description: TTL
        default: 8

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Deployment Service
        run: |
          curl -X POST https://new-forge-service/api/deploy \
          -H "Authorization: Bearer ${{ secrets.STAGING_SERVICE_TOKEN }}" \
          -d '{"branch": "${{ github.ref_name }}", "ttl": ${{ github.event.inputs.ttl }}}}'
